name: Matrix
on: push

jobs: 
  node-version:
    strategy:
      matrix: # rerun job based on variables
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        include: # include variables in occasion that the os and node_Version match
          - os: ubuntu-latest
            node_version: 8
            is_main_configuration: "true"
        exclude: 
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
          - os: windows-latest
            node_version: 10
      max-parallel: 3 # limit jobs running in parallel
      fail-fast: true # if one fails all will stop
    runs-on: ${{ matrix.os }}
    env: 
      IS_MAIN_CONFIGURATION: ${{ matrix.is_main_configuration }}
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Log ${{ matrix.os }} => ${{ matrix.node_version }}
      run: |
        node -v
        echo $IS_MAIN_CONFIGURATION